### ISSUE TITLE
添加定向ts服务器地址功能

### ISSUE THREAD

**Issue by Fa1nttt** [Zahariel1942/koishi-plugin-teamspeak#1]
如题，我手下有多个服务器，能否在插件中添加指向服务器地址来满足多服务器或异地部署bot导致插件无法使用的需求
*可以只为插件添加指向服务器，如果有多个服务器直接使用koishi中的克隆插件即可

**Comment by Zahariel1942** [comment]
自用没想到还有别人用😂，这个不费劲，抽空改一下
2024年6月4日 +0800 19:42 Fa1nttt ***@***.***>，写道：

**Comment by Fa1nttt** [comment]
我特喜欢这插件哈哈哈哈哈哈哈哈哈，挺好用的

**Comment by Fa1nttt** [comment]
还想问一下，可以同时给两个群聊发服务器进入信息嘛

**Comment by Zahariel1942** [comment]
试试 1.1.0 版本

**Comment by Fa1nttt** [comment]
好的谢谢大佬
